/**
 * Signature Event Pool
 * The defining ordeals or set-pieces of a shift. Rare, high-impact events
 * that shape the entire day. At most one per shift.
 *
 * Each event: id, title, desc, station, duration (10-20s), effects,
 * ignoreEffects, canDefer, tier: 'signature'.
 */

export const SIGNATURE_EVENTS = [
  {
    id: 'sig_dea_audit',
    title: 'DEA AUDIT',
    desc: 'Federal agents at the counter. Every controlled substance must be accounted for.',
    station: 'verify',
    duration: 18,
    effects: { safety: -12, scrutiny: -10, burnout: 10, queue: 6 },
    ignoreEffects: { safety: 15, scrutiny: 14, burnout: 6 },
    canDefer: false,
    tier: 'signature',
  },
  {
    id: 'sig_system_meltdown',
    title: 'TOTAL SYSTEM MELTDOWN',
    desc: 'Every screen is down. Phone system too. Paper only.',
    station: 'verify',
    duration: 20,
    effects: { queue: 10, safety: 6, burnout: 12, rage: 5 },
    ignoreEffects: { queue: 8, safety: 8, burnout: 6 },
    canDefer: false,
    tier: 'signature',
  },
  {
    id: 'sig_flu_shot_frenzy',
    title: 'FLU SHOT FRENZY',
    desc: 'Corporate pushed a walk-in flu shot promo. 40 people showed up.',
    station: 'consult',
    duration: 16,
    effects: { queue: 8, burnout: 10, rage: 4, safety: -4 },
    ignoreEffects: { queue: 8, rage: 6, scrutiny: 5 },
    canDefer: false,
    tier: 'signature',
  },
  {
    id: 'sig_karen_supreme',
    title: 'KAREN SUPREME',
    desc: 'Demands manager, then district manager, then corporate number. Films everything.',
    station: 'pickup',
    duration: 14,
    effects: { rage: -15, burnout: 8, scrutiny: -6 },
    ignoreEffects: { rage: 14, scrutiny: 8 },
    canDefer: false,
    tier: 'signature',
  },
  {
    id: 'sig_pharmacist_down',
    title: 'PHARMACIST DOWN',
    desc: 'Your partner pharmacist collapsed. You are alone.',
    station: 'verify',
    duration: 15,
    effects: { burnout: 12, safety: 6, queue: 8, scrutiny: 4 },
    ignoreEffects: { safety: 10, burnout: 8, scrutiny: 6 },
    canDefer: false,
    tier: 'signature',
  },
  {
    id: 'sig_the_long_wait',
    title: 'THE LONG WAIT',
    desc: 'Patient has been waiting 3 hours. They are calm. That makes it worse.',
    station: 'pickup',
    duration: 12,
    effects: { rage: -10, burnout: 8, scrutiny: -4 },
    ignoreEffects: { rage: 12, scrutiny: 6 },
    canDefer: false,
    tier: 'signature',
  },
  {
    id: 'sig_opioid_dilemma',
    title: 'OPIOID DILEMMA',
    desc: 'Script looks legit but something feels wrong. Fill or refuse?',
    station: 'verify',
    duration: 14,
    effects: { safety: -10, burnout: 6, scrutiny: -5 },
    ignoreEffects: { safety: 14, scrutiny: 8 },
    canDefer: false,
    tier: 'signature',
  },
  {
    id: 'sig_power_outage',
    title: 'POWER OUTAGE',
    desc: 'Lights out. Generator covers fridges but not computers.',
    station: 'verify',
    duration: 18,
    effects: { queue: 10, safety: 8, burnout: 10 },
    ignoreEffects: { safety: 10, queue: 8 },
    canDefer: false,
    tier: 'signature',
  },
  {
    id: 'sig_board_inspector',
    title: 'BOARD INSPECTOR',
    desc: 'State board of pharmacy. Unannounced. Full review.',
    station: 'verify',
    duration: 16,
    effects: { safety: -10, scrutiny: -12, burnout: 8 },
    ignoreEffects: { safety: 14, scrutiny: 16, burnout: 5 },
    canDefer: false,
    tier: 'signature',
  },
  {
    id: 'sig_the_recall',
    title: 'THE RECALL',
    desc: 'Nationwide recall. Pull all stock. Contact every patient who filled it.',
    station: 'verify',
    duration: 20,
    effects: { safety: -14, queue: 8, burnout: 12, scrutiny: -4 },
    ignoreEffects: { safety: 16, scrutiny: 10, burnout: 6 },
    canDefer: false,
    tier: 'signature',
  },
];
